coverage:
  range: 50..70
  round: down
  precision: 2
parsers:
  go:
    partials_as_hits: true
ignore:
    - "svc/cmd/*"
    - "svc/runner/*"
    - "svc/testing/*"
    - "svc/handler/*"
    - "svc/middleware/*"
    - "svc/uc/*"
