name: go test with firestore emulator
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          echo "ENV_LOCATION=$GITHUB_WORKSPACE/pkg/setting/files/setting.develop.yaml"
          echo "ENV_LOCATION=$GITHUB_WORKSPACE/pkg/setting/files/setting.develop.yaml" >> $GITHUB_ENV
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Install Cloud beta components'
        run: |
          gcloud components install beta --quiet
      - name: 'Run Firestore Emulator'
        run: |
          gcloud beta emulators firestore start --quiet &
      - name: 'Waiting for the emulator to start up'
        run: sleep 5
      - name: Run tests
        run: go test -v ./...