name: GoTestFirebaseEmulator
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - '**.go'
      - '.github/**'
jobs:
  go-test-with-firebase-emulator:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          echo "ENV_LOCATION=$GITHUB_WORKSPACE/pkg/setting/files/setting.testing.yaml"
          echo "ENV_LOCATION=$GITHUB_WORKSPACE/pkg/setting/files/setting.testing.yaml" >> $GITHUB_ENV
      - name: Install firebase-emulator
        run: npm install -g firebase-tools
      - name: Run Firebase Emulator
        run: |
          firebase setup:emulators:database
          firebase emulators:start --only database &
      - name: 'Waiting for the emulator to start up'
        run: sleep 20
      - name: Run tests
        env:
          FIREBASE_DATABASE_EMULATOR_HOST: localhost:9000
        run: go test -p=1 -race -coverprofile=coverage.txt -covermode=atomic ./... #gosetup
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4