name: go test with firebase emulator
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - '**.go'
jobs:
  go-test-with-base-emulator:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          echo "ENV_LOCATION=$GITHUB_WORKSPACE/pkg/setting/files/setting.testing.yaml"
          echo "ENV_LOCATION=$GITHUB_WORKSPACE/pkg/setting/files/setting.testing.yaml" >> $GITHUB_ENV
      - name: Install firebase-emulator
        run: npm install -g firebase-tools
      - name: Run Firebase Emulator
        run: |
          firebase setup:emulators:database
          firebase emulators:start --only database &
      - name: 'Waiting for the emulator to start up'
        run: sleep 5
      - name: Run tests
        env:
          FIREBASE_DATABASE_EMULATOR_HOST: localhost:9000
        run: go test -v ./... -parallel 1 -count 1