name: go test with firestore emulator
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          echo "ENV_LOCATION=$GITHUB_WORKSPACE/pkg/setting/files/setting.develop.yaml"
          echo "ENV_LOCATION=$GITHUB_WORKSPACE/pkg/setting/files/setting.develop.yaml" >> $GITHUB_ENV
      - name: Install firebase
        run: curl -sL https://firebase.tools | bash
      - name: Run firebase emulators
        run: firebase setup:emulators:firestore
      - run: firebase emulators:start --only firestore &
      - run: sleep 5
      - name: Run tests
        run: go test -v ./...